# https://github.com/DataDog/slapr

name: Slack emoji PR updates
on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [closed]

permissions: {}

jobs:
  run_slapr:
    runs-on: ubuntu-latest
    environment:
      name: main
    steps:
    - uses: DataDog/slapr@f4337a20eedf6b840f6d85ee2399f1ee86f109d7 # master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        slack-api-token: ${{ secrets.SLACK_TOKEN }}
        slack-channel-id: C06P2KX149M
        bot-user-id: UTMS06TPX
        emoji-review-started: review_started
        emoji-approved: approved
        emoji-changes-requested: changes_requested
        emoji-merged: merged
        emoji-closed: closed
